theme: jekyll-theme-minimal
title: Ramkrishnan Thevar (rk)
share-description: Tech Enthusiast | Software Developer | Freelancer.

# Google Analytics
google_analytics: G-BBWJS9BN5D


twitter_username: 1rkthevar  
github_username:  1Ramkrishnan
facebook_username: ramkrishnan.thevar
linkedin_username: 1ramkrishnan

